name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install modules
        run: yarn

      - name: Run JavaScript
        if: always()
        run: yarn lint-js

      - name: Run TypeScript
        if: always()
        run: yarn lint-tsc
